app: binance-leaderboard-bot
service: binance-leaderboard-bot

frameworkVersion: "2 || 3"

plugins:
  - "serverless-python-requirements"

layers:
  pybinance:
    path: layers/pybinance
    description: >
      Lambda layer contains helper functions for aws services 
      and other common functions to avoid repeating the code.
    compatibleRuntimes:
      - python3.9

custom:
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.9
  architecture: arm64
  region: ${opt:region, 'us-east-1'}
  # region: ${opt:region, 'eu-west-3'} # France, Paris
  stage: ${opt:stage, 'dev'}
  timeout: 60
  versionFunctions: false

  environment:
    SERVICE_NAME: ${self:service}
    TELEGRAM_BOT_API_KEY: 5280766845:AAFXfHgOeuTUbXlDOF_bcsKIs8H_jWQ1O-Q
    TELEGRAM_CHAT_ID: -666728785

  stackTags:
    "name": ${self:service}

package:
  excludeDevDependencies: true
  patterns:
    - "!node_modules/**"
    - "!requirements.txt"
    - "!README.md"
    - "!.gitignore"
    - "!dev/**"
    - "!layers/**"
    - "!.venv/**"

functions:
  binanceBot:
    handler: src.handlers.bot.index.handler
    description: Main bot handler.
    memorySize: 1024 # test increase to compare time
    layers:
      - !Ref PybinanceLambdaLayer
    # events:
      # - schedule: rate(5 minutes) # TEST
      # - schedule: rate(30 minutes) # PRODUCTION
      # - schedule: rate(1 hour) # PRODUCTION
      # - schedule: rate(n hours) # PRODUCTION


